AP_Proximity: correct compialtion when hexsoon radar not compiled in
../../libraries/AP_Proximity/AP_Proximity.cpp: In member function 'void AP
_Proximity::init()':
../../libraries/AP_Proximity/AP_Proximity.cpp:231:20: error: 'Hexsoon_Rada
r' is not a member of 'AP_Proximity::Type'
  231 |         case Type::Hexsoon_Radar:
      |                    ^~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.