AP_Bootloader: correct compilation when signing enabled
In file included from ../../libraries/AP_CheckFirmware/AP_CheckFirmware.cpp:13:
../../libraries/AP_CheckFirmware/../../Tools/AP_Bootloader/support.h:57:25: error: "CH_CFG_USE_HEAP" is not defined, evaluates to 0 [-Werror=undef]
   57 | #if defined(STM32H7) && CH_CFG_USE_HEAP
      |                         ^~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors